### ISSUE TITLE
Support for ASIN as an output scheme keyword

### ISSUE THREAD

**Issue by tylernguyen** [djdembeck/bragibooks#124]
Hi,

My preferred directory scheme is:

Author
  - Book (Year) [ASIN]
      - Book - Subtitle (Year)

Please add support for ASIN an output scheme keyword. This would also be helpful considering that `Audnexus.bundle` can quickmatch if there is an ASIN present in the folder name.

**Comment by djdembeck** [comment]
Added in `latest` https://github.com/djdembeck/bragibooks/pull/132
