### ISSUE TITLE
Server Error (500) after Submit ASINs

### ISSUE THREAD

**Issue by tdk1069** [djdembeck/bragibooks#129]
Hi, Running the docker image with input/output/config mapped to values of current directory.

Container fires up. Import Tab shows me my first book to convert, select, next, go with defaults on the initial config, Submit ASINs I have entered B00QXW6NY6 and B00PCV52EQ (com and co.uk respectively) co.uk gives me bad ASIN number, com ASIN sits and whirls for a while then gives me Server Error (500) 

I've tried opening up permissions in case it was related, changing UID/GID deleting and recreating etc. I've tried with a couple of books from different authors incase it was a particular book/author issue.

log attached. 
[bragibooks.txt](https://github.com/djdembeck/bragibooks/files/10499703/bragibooks.txt)

**Comment by djdembeck** [comment]
Hello,

Bragibooks hasn't been updated for regions other than US yet: https://github.com/djdembeck/bragibooks#-usage-

**Comment by tdk1069** [comment]
Hiya, 
I had already tried the us code (see above) What I have just noticed is that searching the title for the ASIN returned two books of the same name, I picked the other one (same author/book different year) and it worked. This was the same for the next 2 or 3 books, .com returns 2 numbers one works, one gives Server Error (500). But I have now gotten to another book (Moon over Soho - Ben Aaronovitch, gives me two numbers B005CW3NN2 and B009CZN2AE (both from .com) which both give me Server Error (500)
