### ISSUE TITLE
Chapters not being added?

### ISSUE THREAD

**Issue by sizzleweet** [djdembeck/bragibooks#225]
Hello,

Just wondering how chapter support is being handled.

I've tried a handful of books and none of them have anything in the "chapters" text file.  Some of them were individual mp3s, some of them were already chapterized m4b files.

Do chapters only work if they are single files?

I have chapterized mp3 files for some books as well as some broken into cd "tracks".

Is there a method for getting those setup for chapters with this tool? or even just outputting the chapter 

Sorry if this isn't the right place for this question.

**Comment by djdembeck** [comment]
From the features readme:
"Chapter times/titles (only when input is m4b or a single mp3) - written as tags and chapters.txt."
