### ISSUE TITLE
Hidden files causing program to stop processing files

### ISSUE THREAD

**Issue by partymike** [djdembeck/bragibooks#232]
I run this in docker on a QNAP NAS, unofrtunatly the program detects hidden files/folders generated by the system:

.@__thumb

This causes the software to throw an integer error and stops processing, there is no way manually unselect the files (especially in a folder with multiple mp3 you want to process into 1 file) or any option to ignore file types/hidden files.

Currenlty the ony workaround is to delete the files manually "find . -type d -name .@__thumb -delete" and then everything works.

Could an option be added to ignore files types/hidden files (as they wouldn't be relevant to the process)

**Comment by djdembeck** [comment]
That is unexpected, because we use [iterdir()](https://docs.python.org/3/library/pathlib.html#pathlib.Path.iterdir), which states 
> special entries '.' and '..' are not included

I am not familiar with QNAP, so unfortunately this may be caused by their OS.
