### ISSUE TITLE
Add Chapters to books using AudNexus

### ISSUE THREAD

**Issue by pumhood** [djdembeck/bragibooks#256]
Feature Request here - Could you use AudNexus to grab the chapter data for the books and add chapters to them during processing? This would be immensely useful.  I know AudNexus chapter data (and Audible chapter data in general) is not the best, but it is better than none...

**Comment by djdembeck** [comment]
As you can see from the readme (for more features), `m4b-merge` says this:

```
Chapter times/titles (only when input is m4b or a single mp3) - written as tags and chapters.txt.
```
