### ISSUE TITLE
Incorrect playback time if greater than 24 hours

### ISSUE THREAD

**Issue by jansendotsh** [djdembeck/bragibooks#48]
This is a pretty small bug report since it doesn't impact book management. If a book has a playback time longer than 24 hours, the playback timeon the confirm screen will only display times past a full day. For an example, this [book](https://www.audible.com/pd/Directorate-S-Audiobook/B075DJYSCT?qid=1634344534&sr=1-1&ref=a_search_c3_lProduct_1_1&pf_rd_p=83218cca-c308-412f-bfcf-90198b687a2f&pf_rd_r=F15ST9KMF145RY86H0QZ) has a playback time of roughly 28:30 but bragibooks only shows 4:30.

**Comment by djdembeck** [comment]
Good catch! The post-process page needs a lot of love someday, but for now, this has been fixed by https://github.com/djdembeck/bragibooks/pull/49

You can either test it using the `:develop` tag for the repo or wait till it's merged to main.

**Comment by djdembeck** [comment]
Now in main
