### ISSUE TITLE
Docker Url Prefix

### ISSUE THREAD

**Issue by gnuyen** [djdembeck/bragibooks#54]
Is there a way to add an --url-prefix for the docker?   You could use FORCE_SCRIPT_NAME = '/bragibooks' on that, so people could use reverse proxies with bragibooks.

Thanks

**Comment by gnuyen** [comment]
adding --env SCRIPT_NAME=/bragibooks to the gunicorn start might work as well, where you get bragibooks from a docker variable

**Comment by djdembeck** [comment]
This is easily achievable with either Traefik or rewrites on nginx: https://serverfault.com/a/379679
