### ISSUE TITLE
Server Error (500) on macOS installation

### ISSUE THREAD

**Issue by seannymurrs** [djdembeck/bragibooks#60]
I installed bragibooks on my M1 Mac mini in an attempt to avoid the slowness I’ve experienced with the Docker version. I followed the installation instructions, but I received the following error after submitting a list of ASINs:

```
Internal Server Error: /import/match
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/homebrew/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/sean/bragibooks/importer/views.py", line 102, in post
    helpers.validate_asin(asin)
TypeError: validate_asin() missing 1 required positional argument: 'asin'
```

**Comment by djdembeck** [comment]
If you are installing directly, you need to use `develop` branch of Bragi until this is merged: https://github.com/djdembeck/bragibooks/pull/55

The docker `main` image for Bragi ships a compatible version of m4b-merge before the settings changes.

**Comment by seannymurrs** [comment]
Thanks. Sorry if this is a dumb question, but how would I switch branches at this point?Sean MurrayOn Thu, Nov 18, 2021 at 5:14 PM,             David Dembeck ***@***.***> wrote:
If you are installing directly, you need to use develop branch of Bragi until this is merged: #55
The docker main image for Bragi ships a compatible version of m4b-merge before the settings changes.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/djdembeck/bragibooks/issues/60#issuecomment-973315909",
"url": "https://github.com/djdembeck/bragibooks/issues/60#issuecomment-973315909",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by garlik82** [comment]
I had this issue. m4b-merge cli works just fine, so I assume it's something with the web server. My workaround was to build a bragibooks arm64 docker image. M1 runs amd64 docker images in rosetta so that might explain the slowness you experienced while running it over docker.

**Comment by seannymurrs** [comment]
> I had this issue. m4b-merge cli works just fine, so I assume it's something with the web server. My workaround was to build a bragibooks arm64 docker image. M1 runs amd64 docker images in rosetta so that might explain the slowness you experienced while running it over docker.

Could you share your arm64 docker image (or share how you built it)?

**Comment by garlik82** [comment]
> > I had this issue. m4b-merge cli works just fine, so I assume it's something with the web server. My workaround was to build a bragibooks arm64 docker image. M1 runs amd64 docker images in rosetta so that might explain the slowness you experienced while running it over docker.
> 
> Could you share your arm64 docker image (or share how you built it)?

Sure. hope there's no problem with @djdembeck. it's not up to date with latest m4b-merge but it works fine. garlik82/bragibooks:arm64 on dockerhub. I'll set it to public.

**Comment by djdembeck** [comment]
I'm also open to PRs if you want to merge your work in!

**Comment by garlik82** [comment]
I’m not a coder. I just know my way around code and changed what I had to change do build an arm64 compatible image.

**Comment by djdembeck** [comment]
The original issue is resolved now, closing.
