### ISSUE TITLE
Always getting a "Bad ASIN"

### ISSUE THREAD

**Issue by KevinDenis** [djdembeck/bragibooks#62]
I'm probablly not using the app correctly, but I'm always getting a bad asin :
![image](https://user-images.githubusercontent.com/19326280/144841154-830559ee-2e7c-4622-8bb1-fc1c97b955bb.png)

**Comment by djdembeck** [comment]
@KevinDenis is that the Harry Potter UK ASIN? Currently, only US region ASINs are supported. I should probably add that to the readme

**Comment by KevinDenis** [comment]
OK, works now, thanks for the help !

**Comment by baloodusudouest** [comment]
hi, i try for ex the last JK Rowling book, the christmas pig
https://www.amazon.com/The-Christmas-Pig/dp/B092NW9S7H/ref=sr_1_1?crid=RIPOJMI1E8L8&keywords=the+christmas+pig&qid=1647037159&sprefix=the+christmas+pig%2Caps%2C191&sr=8-1

i try the ASIN B092NW9S7H, but i have a bad ASIN.

I am in france, do i have to use bragibooks under vpn located in US?

Thanks

**Comment by djdembeck** [comment]
> hi, i try for ex the last JK Rowling book, the christmas pig https://www.amazon.com/The-Christmas-Pig/dp/B092NW9S7H/ref=sr_1_1?crid=RIPOJMI1E8L8&keywords=the+christmas+pig&qid=1647037159&sprefix=the+christmas+pig%2Caps%2C191&sr=8-1
> 
> i try the ASIN B092NW9S7H, but i have a bad ASIN.
> 
> I am in france, do i have to use bragibooks under vpn located in US?
> 
> Thanks

You must use the audible.com ASIN: Listen to The Christmas Pig by J.K. Rowling on Audible. https://www.audible.com/pd/B092NZ1K9Y

**Comment by baloodusudouest** [comment]
ok, when i done this, i have en server error 500 with the countainer logs following
Validated ASIN: B092NZ1K9Y
Making models and merging files for: J.K. Rowling - Jack et la grande aventure du Cochon de Noël [mp3-128]_cover.jpg
Final path format: J.K. Rowling/The Christmas Pig/The Christmas Pig
Complete output path: /output/J.K. Rowling/The Christmas Pig/The Christmas Pig
Internal Server Error: /import/match
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/app/web/importer/views.py", line 138, in post
    merge_object.run_m4b_merge()
  File "/home/app/web/utils/merge.py", line 50, in run_m4b_merge
    self.m4b.run_merge()
  File "/usr/local/lib/python3.9/site-packages/m4b_merge/m4b_helper.py", line 267, in run_merge
    f" {self.file_title}")
AttributeError: 'M4bMerge' object has no attribute 'file_title'
Not Found: /favicon.ico
