### ISSUE TITLE
Stupid Question: After installing through Docker, how do I actually run the program?

### ISSUE THREAD

**Issue by ReaderGuy42** [djdembeck/bragibooks#70]
I just installed Docker for the first time and successfully installed Bragibooks, or so the terminal thing tells me (I'm on Linux Mint). 

How do I run the program now? From the screenshots I gather it has a GUI but how do I get there? I tried using that line of code you listed under the info on the Docker again, but it tells me this:

```
sudo docker run --rm -d --name bragibooks -v /home/ReaderGuy42/Music/test -v /home/ReaderGuy42/Music/t2 -v /appdata/bragibooks/config:/config -p 8000:8000/tcp -e LOG_LEVEL=WARNING ghcr.io/djdembeck/bragibooks:main
docker: Error response from daemon: Conflict. The container name "/bragibooks" is already in use by container "2dd09b8eb8bc56a11e6838b057d33329584f36294b44af3ebb2e618f1261ad42". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
```
I have no idea what to do now, so any pointers are appreciated :) Thanks!

**Comment by garlik82** [comment]
Use your web browser and http://ip-of-the-machine-running-docker:8000, if using the browser on the same machine just http://localhost:8000

**Comment by ReaderGuy42** [comment]
That gives me a server error

**Comment by garlik82** [comment]
you running that on an amd64 machine? but check the logs, that should help out.

**Comment by ReaderGuy42** [comment]
> you running that on an amd64 machine
How do can I tell? I'm not actually sure.

**Comment by garlik82** [comment]
> > you running that on an amd64 machine
> 
> How do can I tell? I'm not actually sure.

What CPU does it have. run this on your terminal and post your results.

docker logs -f Bragibooks

**Comment by garlik82** [comment]
your docker command is wrong.  this -v /home/ReaderGuy42/Music/test and this -v /home/ReaderGuy42/Music/t2 should be -v /home/ReaderGuy42/Music/t2:/t2 and -v /home/ReaderGuy42/Music/test:/test. before the ':' you specify the host folder you want to direct to the container folder. host folder: ´-v /home/ReaderGuy42/Music/test' then ':' and then container folder: '/t2'.

**Comment by ReaderGuy42** [comment]
If I use `sudo` I get this:
```
chown: cannot access '/input': No such file or directory
chown: cannot access '/output': No such file or directory
Operations to perform:
  Apply all migrations: auth, contenttypes, importer, sessions
Running migrations:
  No migrations to apply.
[2022-01-23 18:01:15 +0000] [12] [INFO] Starting gunicorn 20.1.0
[2022-01-23 18:01:15 +0000] [12] [INFO] Listening at: http://0.0.0.0:8000 (12)
[2022-01-23 18:01:15 +0000] [12] [INFO] Using worker: gthread
[2022-01-23 18:01:15 +0000] [13] [INFO] Booting worker with pid: 13
[2022-01-23 18:01:15 +0000] [14] [INFO] Booting worker with pid: 14
Internal Server Error: /import/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 162, in get
    context = self.get_context_data(**kwargs)
  File "/home/app/web/importer/views.py", line 34, in get_context_data
    for path in sorted(
  File "/usr/local/lib/python3.9/pathlib.py", line 1160, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/home/worker/input'
Not Found: /favicon.ico
```

**Comment by garlik82** [comment]
ok tell me what directory in tour host you want to be the /output folder and the host folder you want for /input folder. I'll write the volumes for you.

**Comment by ReaderGuy42** [comment]
`Test` as input, and `t2` as output, please. Thanks!

**Comment by garlik82** [comment]
-v /home/ReaderGuy42/Music/test:/input and -v /home/ReaderGuy42/Music/t2:/output. delete bragibooks container your created with docker rm --force bragibooks, change your command using this lines and try it again

**Comment by ReaderGuy42** [comment]
Ok, so since `-v` wasn't doing anything I put it back into the combined thing:
```
sudo docker run -v /home/ReaderGuy42/Music/test:/input -v /home/ReaderGuy42/Music/t2:/output -v /appdata/bragibooks/config:/config -p 8000:8000/tcp -e LOG_LEVEL=WARNING ghcr.io/djdembeck/bragibooks:main
```
And now it's sort of stuck after putting this out:
```
Operations to perform:
  Apply all migrations: auth, contenttypes, importer, sessions
Running migrations:
  No migrations to apply.
[2022-01-23 18:28:35 +0000] [11] [INFO] Starting gunicorn 20.1.0
[2022-01-23 18:28:35 +0000] [11] [INFO] Listening at: http://0.0.0.0:8000 (11)
[2022-01-23 18:28:35 +0000] [11] [INFO] Using worker: gthread
[2022-01-23 18:28:35 +0000] [12] [INFO] Booting worker with pid: 12
[2022-01-23 18:28:35 +0000] [13] [INFO] Booting worker with pid: 13
```

**Comment by garlik82** [comment]
> Ok, so since `-v` wasn't doing anything I put it back into the combined thing:
> 
> ```
> sudo docker run -v /home/ReaderGuy42/Music/test:/input -v /home/ReaderGuy42/Music/t2:/output -v /appdata/bragibooks/config:/config -p 8000:8000/tcp -e LOG_LEVEL=WARNING ghcr.io/djdembeck/bragibooks:main
> ```
> 
> And now it's sort of stuck after putting this out:
> 
> ```
> Operations to perform:
>   Apply all migrations: auth, contenttypes, importer, sessions
> Running migrations:
>   No migrations to apply.
> [2022-01-23 18:28:35 +0000] [11] [INFO] Starting gunicorn 20.1.0
> [2022-01-23 18:28:35 +0000] [11] [INFO] Listening at: http://0.0.0.0:8000 (11)
> [2022-01-23 18:28:35 +0000] [11] [INFO] Using worker: gthread
> [2022-01-23 18:28:35 +0000] [12] [INFO] Booting worker with pid: 12
> [2022-01-23 18:28:35 +0000] [13] [INFO] Booting worker with pid: 13
> ```

http://localhost:8000

**Comment by ReaderGuy42** [comment]
Hey, thanks now it works :) Thank you :+1: But now in the program it's telling me that
`Path is not a directory: /home/paul/Music/test` What does this mean?

**Comment by garlik82** [comment]
> Hey, thanks now it works :) Thank you 👍 But now in the program it's telling me that
> `Path is not a directory: /home/ReaderGuy42/Music/test` What does this mean?

did you mkdir test inside the Music folder? I have never seen that error. can you screenshot it and show logs again?

**Comment by djdembeck** [comment]
As Garlik said, make sure the input folder is created before running the docker.

**Comment by ReaderGuy42** [comment]
Um, I tried doing the log command again, but now it's telling me that `Error: No such container: bragibooks`, so I tried removing it again, but it's still not working, even when I input the long string again. Before that, I got this screenshot however:

![Screenshot 2022-01-23 at 19-44-14 Bragi Books](https://user-images.githubusercontent.com/71895400/150693294-4ca1bfd2-c680-4d00-86c9-2caf591b439b.png)

**Comment by garlik82** [comment]
does the test folder exist on the host machine?

**Comment by ReaderGuy42** [comment]
Do you mean in the directory: `/home/ReaderGuy42/Music/test` ? Yes that's a folder called test in Music. Inside test there's an audiobook. Is that what you mean?

**Comment by garlik82** [comment]
yes that's what I mean. can you get logs? @djdembeck could this be a permission thing?

**Comment by ReaderGuy42** [comment]
When I run `docker logs -f bragibooks` it tells me `Error: No such container: bragibooks`

**Comment by djdembeck** [comment]
> yes that's what I mean. can you get logs? @djdembeck could this be a permission thing?

Quite possibly related to this https://github.com/djdembeck/bragibooks/issues/67#issuecomment-1012725205



> When I run `docker logs -f bragibooks` it tells me `Error: No such container: bragibooks`

You didn’t use —name bragibooks in the run command, so it’s been assigned a random name. You can find it by doing docker ps

**Comment by garlik82** [comment]
do this: docker container ls

**Comment by ReaderGuy42** [comment]
> > yes that's what I mean. can you get logs? @djdembeck could this be a permission thing?
> 
> Quite possibly related to this [#67 (comment)](https://github.com/djdembeck/bragibooks/issues/67#issuecomment-1012725205)
> 
> > When I run `docker logs -f bragibooks` it tells me `Error: No such container: bragibooks`
> 
> You didn’t use —name bragibooks in the run command, so it’s been assigned a random name. You can find it by doing docker ps

Ok, so I do `sudo docker ps` and get this:
```
sudo docker ps
CONTAINER ID   IMAGE                               COMMAND                  CREATED          STATUS          PORTS                                       NAMES
9de8d926690e   ghcr.io/djdembeck/bragibooks:main   "/bin/sh docker/entr…"   50 minutes ago   Up 50 minutes   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp   admiring_snyder
```

**Comment by garlik82** [comment]
docker logs -f 9de8d926690e 
@djdembeck he ins't running docker as root. maybe this is the problem?

**Comment by djdembeck** [comment]
Perfect. So For ease of use, I’d recommend running docker rm 9de8d926690e
And then running `sudo docker run —name bragibooks -v /home/ReaderGuy42/Music/test:/input -v /home/ReaderGuy42/Music/t2:/output -v /appdata/bragibooks/config:/config -p 8000:8000/tcp -e LOG_LEVEL=WARNING ghcr.io/djdembeck/bragibooks:main`

**Comment by ReaderGuy42** [comment]
Ok, great, did all that, and now for `sudo docker logs -f bragibooks` I get this:
```
sudo docker logs -f bragibooks
Operations to perform:
  Apply all migrations: auth, contenttypes, importer, sessions
Running migrations:
  No migrations to apply.
[2022-01-23 19:25:30 +0000] [11] [INFO] Starting gunicorn 20.1.0
[2022-01-23 19:25:30 +0000] [11] [INFO] Listening at: http://0.0.0.0:8000 (11)
[2022-01-23 19:25:30 +0000] [11] [INFO] Using worker: gthread
[2022-01-23 19:25:30 +0000] [12] [INFO] Booting worker with pid: 12
[2022-01-23 19:25:30 +0000] [13] [INFO] Booting worker with pid: 13
```
(BTW in your previous comment the hyphen before the `name` was giving me trouble so I used two, so: `--name` and that worked)

**Comment by garlik82** [comment]
you could try mkdir done inside the test folder and restart the container with docker restart bragibooks. see if we can get more from the logs.

**Comment by ReaderGuy42** [comment]
I'm not sure how to do that, sorry. I tried doing `mkdir test` from within Music, but that just tells me that the folder already exists. How do I do that?

**Comment by garlik82** [comment]
within Music do:
cd test
mkdir done

**Comment by ReaderGuy42** [comment]
Ok, now what?

**Comment by garlik82** [comment]
Restart the container

**Comment by ReaderGuy42** [comment]
Ok, then I use the long command again and then it tells me 
```
docker: Error response from daemon: Conflict. The container name "/bragibooks" is already in use by container "832d2624ac6a947b002e7741791afe044e3187f9ea29bc2f65e313ff5efafca3". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
```

**Comment by garlik82** [comment]
Just do docker restart bragibooks and http://localhost:8000

**Comment by ReaderGuy42** [comment]
Ok, but I'm still having the same error message . . .

**Comment by garlik82** [comment]
do id yourusername in your terminal and post results. bragibooks user worker as a uid:gid=1000:1000, I think your linux uid:gid must be different. but I'm just guessing, I don't know much about permissions.

**Comment by ReaderGuy42** [comment]
Hey thanks guys, I think I'm going to give up at this point. I really appreciate the help, but I'll just use easyTag for now. Thanks though :)
