### ISSUE TITLE
Synology Docker - Server Error (500)

### ISSUE THREAD

**Issue by rendyhd** [djdembeck/bragibooks#78]
I've been getting a Server Error (500) when trying to process multi-file books. What I've found in the log is that it always errors with the `@eaDir` file (an invisible folder that Synology automatically generates to create metadata).
If I process a single file in the input folder (full length .mp3) it works without issues.
I'm starting to think the issue is the `@eaDir` file/folder, which is being processed as a NoneType in python.

<img width="1138" alt="Screenshot 2022-02-16 at 16 39 47" src="https://user-images.githubusercontent.com/48726661/154300319-9bfb2cbf-7995-4d6a-9934-ea1ab00b54be.png">

(made a new issue next to #67 because rights don't seem to be an issue for me. I get the Server Error after submitting ASIN.

**Comment by djdembeck** [comment]
I cannot reproduce this by simply making that folder in my input folder and processing something. However, this may fix the issue for you: https://github.com/djdembeck/m4b-merge/pull/51
