### ISSUE TITLE
package mp4v2-utils does not exist

### ISSUE THREAD

**Issue by WeisseTeetasse** [djdembeck/bragibooks#94]
Anymore

**Comment by djdembeck** [comment]
Can you be more specific? Are you getting an error? If so, where?

**Comment by WeisseTeetasse** [comment]
https://packages.ubuntu.com/search?keywords=mp4v2-utils&searchon=names&suite=jammy&section=all

the package does not exist in current ubuntu versions. The last Ubuntu version to have that package was 18.04.
