### ISSUE TITLE
completed audiobooks are not moved into the 'done' folder *sometimes*

### ISSUE THREAD

**Issue by WeisseTeetasse** [djdembeck/bragibooks#96]
Are there any logs I can look at to debug that?
Also could there be an option to just delete the completed books or should I link output/done to /dev/null?

**Comment by djdembeck** [comment]
This should be fixed/easier to narrow down when `m4b-merge` gets bumped to `0.4.10` in the docker here.

**Comment by jcrmit** [comment]
Hi @djdembeck - I think I am running into this issue. But I cannot get a single converstion to appear in the dowloads folder - the Author Name and Book folder appear, but not the MB4. I tried without folders in the naming scheme, not change. I do not think it is folder permission. 

`Applying chapters to m4b...
job begin: /mnt/downloads/bragibooks/Red War.m4b
Importing 56 QuickTime and Nero chapters from file /mnt/downloads/bragibooks/Red War.chapters.txt into file "/mnt/downloads/bragibooks/Red War.m4b"
closing /mnt/downloads/bragibooks/Red War.m4b
optimizing /mnt/downloads/bragibooks/Red War.m4b`

Any thoughts...
